{% set name = "radtraq" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/RadTraQ-{{ version }}.tar.gz
  sha256: 1ac8bde0e918cbb610b1a73f54d10132c94ae1d2caf2db14db1aa1a8dea861d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - pandas
    - act-atmos
    - numpy
    - scipy
    - xarray
    - matplotlib-base
    - netcdf4
    - pint
    - open-radar-data

test:
  imports:
    - radtraq
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ARM-Development/RadTraQ/
  summary: Python package for weather radar quality tracking
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AdamTheisen
    - akrherz
    - mgrover1
    - zssherman
