{% set name = "radtraq" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/RadTraQ-{{ version }}.tar.gz
  sha256: 574e500d60cae5a6f2f2beee1c6402a61e90c358a7b5f5c92ea78608b6279897

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - pandas
    - act-atmos
    - numpy
    - scipy
    - xarray
    - matplotlib-base
    - netcdf4
    - pint

test:
  imports:
    - radtraq
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ARM-Development/RadTraQ/
  summary: Python package for weather radar quality tracking
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AdamTheisen
    - akrherz
    - mgrover1
    - zssherman
